name: DailyTest

on:
  schedule:
    - cron: '0 8 * * 1-5'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16, 18]
    
    services:
      mongodb:
        image: mongo:4.0.18
        ports:
          - 27017:27017
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install pm2
      run: npm install -g pm2
    - name: Install FoalTS CLI
      run: npm install -g @foal/cli
    - name: Run acceptance tests (Bash)
      run: ./e2e_test.sh
